version: 1
disable_existing_loggers: False
filters:
  request_id:
    (): price_model.utils.log_util.RequestIdFilter
formatters:
  standard:
    format: '%(asctime)s - %(name)s.%(module)s.%(funcName)s:%(lineno)d - %(levelname)s - %(request_id)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    filters: ['request_id']
loggers:
  price_model:
    level: DEBUG
    handlers: [console]